title: Rachel Estilo
# author: Rachel Estilo
# description: >- # this means to ignore newlines until "baseurl:"
#   Page description, a short description of this page coming soon.
url: http://racstyle.github.io/ # the base hostname & protocol for your site, e.g. http://example.com


# Collection for "pages"
collections:
  pages:
    output: true


# Prevent Jekyll from processing these files BUT include in the build folder.
include:
  - node_modules
  - pages
  - .htaccess


# Exclude from processing.
exclude:
  - node_modules/foundation-sites/docs/
  - config.codekit3